//import org.junit.Test;
//import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'SGcom' at '16. 3. 15 오후 5:03' with Gradle 2.9
 *
 * @author SGcom, @date 16. 3. 15 오후 5:03
 */
/*
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
*/